package com.sandwich.client;

public class ClientForbiddenException extends Exception {
	// Autogenerated crap in case you want to serialize your BootstrapForbiddenException :/
	private static final long serialVersionUID = 6046497135240847427L;
}
